### ISSUE TITLE
Thank you - Auto Fan not work

### ISSUE THREAD

**Issue by NucleaR-II** [cryptopoo/hiveos_gddr6x_temps#1]
Now the mem temperatures are visible in Hive OS, but unfortunately Autofan does not respond, it ignores the mem temperatures.

Thanks for the work

**Comment by cryptopoo** [comment]
Hi!

Thanks for reporting it, I will have a look :)

I'm trying to be the least invasive as possible in respect to HiveOS, so I will see later tonight if there is a way to let autofan work correctly without "touching" it :)

Will keep you posted!

**Comment by cryptopoo** [comment]
Hello!

I have investigated the autofan functionality and I have a good and a bad news. I will start with the bad one.

The code in the autofan script by HiveOS is basically mostly the same for AMD and NVIDIA gpus. The only difference, guess what, is that the code that handles nvidia auto fan doesn't make use of the memory temps, while the AMD code does.

The "good" news is that patching the autofan module would require just 3 additional lines + 1 modification on one line to make the magic happen.

Since modifying HiveOS core functionality is not in the scope of this module (althought I would really really like to help having this embedded in the script, it will make the scope too broad to be supported by the little time I have) I will think on how to proceed, if whether add some additional scripts to this module or just provide those 4 lines in a section of the README.
So far I have tested it and it behaves correctly on my installations.

Will keep you posted!

**Comment by cryptopoo** [comment]
Hello there,

I've added a patch for autofan. You can see on README how to install it. Make sure to re-install the module first with quick-install.sh and then install the autofan patch!

Let me know how it goes ;)

**Comment by smdbg** [comment]
It works! But auto fan logic sucks little bit, especially whit 2C steps, but if entered odd values everything is OK - dream came true :)

**Comment by cryptopoo** [comment]
I guess that's the way autofan works with memory temp, we just give it some temps :)

Personally I use 95C on temp for autofan and seems to be working fine. Never tried with even values, but well overall I can't complain either. In one rig works better than another as well. But it is what is :)

**Comment by NucleaR-II** [comment]
Autofan works now - THANK YOU SO MUCH!!!!
