### ISSUE TITLE
Not working on mixed gpu/miners

### ISSUE THREAD

**Issue by hatnunes** [cryptopoo/hiveos_gddr6x_temps#2]
Hello,
I have this configuration, and only the first GPU reports memory temperature.

![image](https://user-images.githubusercontent.com/83378149/159749189-7ac4f8d8-83e2-442b-a689-e55968a97950.png)

At least to my understanding all GPUs on gminer should report mem temps.

![image](https://user-images.githubusercontent.com/83378149/159749928-960c6f9c-b048-45bd-9d97-57a0f073eb88.png)

On other 2 rigs is working flawless, there although the GPU are sequential on the miners.

Thank you, for the good work.

**Comment by cryptopoo** [comment]
Hello there!

This scenario is something I haven't tested, but I can already see what can be improved.

I will let you know as soon as I have more info :)

**Comment by cryptopoo** [comment]
Hello there!

I just pushed some fixes to add support for the 3070 Ti, so those temperatures should show up as well.

From your screenshots I can see that GPU3 (3080) is on lolminer. Unfortunately that miner doesn't report the memory temperature (yet), so I can't extract the readings from its logs.

You could eventually put GPU1 and GPU3 on t-rex and GPU5 alone on lolminer. This way all temps should be reported.

You can run again the installation command and your script should be updated and running.

Please let me know it helps / works :pray: ! Cheers!

**Comment by hatnunes** [comment]
Hello, 

It's working now, the 3070Ti is reporting memory temperature. 

![image](https://user-images.githubusercontent.com/83378149/159808423-b7963e50-fd0b-40c3-996b-f6c2193ded85.png)

I'm aware that lolminer don't yet support memory temp reading. But because we have different wallets, has to stay that way :)

I was looking into your code, and was thinking if the "script" detects 2 temperature readings (on same line - gpu) could report independently if the gpu is a 3xxx series or not. Like my 2080Ti now is reporting memory temp since they added sensor reading.

Thanks!

**Comment by cryptopoo** [comment]
Hi,

I was thinking that (your last solution) also and assumed initially that it wasn't needed for other cards.

Just so I know a bit more about the 2080 Ti, did it show up memory readings before in HiveOS already? Or did they add memory readings just in the miner(s)?

Overall, I prefer to be more explicit on the data I collect just to "invade" the least possible the data that HiveOS already gather from other sources (aka the driver, like it does for AMD cards). This way I contain the risk of eventually contaminating data just in case my script misbehaves. In other words I limit the scope so that I limit the damage.

I will add the 2080 Ti to the list for now (if you know more other models, please let me know) and then I will consider better all the implications of collecting the information of any card, 30xx series or not :)

**Comment by hatnunes** [comment]
Hello,

Working!

The 2080Ti memory temp read was added on the same update as others RTX 3xxx. And I don´t really know if all 2080Ti support VRAM temp reading.

Yesterday I've read this post:

https://www.reddit.com/r/EtherMining/comments/tkglwx/3060_ti_memory_temperature/

Appears that some 3060Ti report VRAM Temp.

Thanks!

**Comment by cryptopoo** [comment]
Hi,

that's nice to read. While somebody there thinks whether some partner put memory sensors or not, there is to say that memory sensors are embedded into the memory chips. That data (memory temperature) doesn't transit on dedicated pins, but is read via commands sent to the memory chip itself.

So, all in all, what I believe it really is, is that some BIOS have simply implemented that call while some have not. 

I'm glad to know there is more cards and that everything works fine for your rig!
