### ISSUE TITLE
autofan

### ISSUE THREAD

**Issue by mmll1** [cryptopoo/hiveos_gddr6x_temps#21]
Autofan mem temp doesn't work, tried stable and unstable version

**Comment by dedizones** [comment]
**hello 

have you tried the patch?**

_Make autofan work with NVIDIA memory temps
In order for autofan to work with NVIDIA cards memory temperatures, you will need to apply a small patch to the autofan HiveOS script.
Since this is a change to a core file of HiveOS, this hasn't been included in the normal quick-install.sh script and you will have to apply it manually after installing this add-on. The patch is very simple, it passes memory temperatures to the function responsible for adjusting fan speed, just like it does for AMD cards, nothing different than that. There is no real alteration of the behavior of how the autofan module works per-se, so you can expect it to work as usual. Please make sure to run on latest version of HiveOS before applying the patch and bear in mind that updating HiveOS might revert this patch (so you may need to apply it again):_

`curl https://raw.githubusercontent.com/cryptopoo/hiveos_gddr6x_temps/main/patch-autofan.sh | bash`

_The patch will be reverted if you uninstall this module._

**Comment by Chase817** [comment]
I have applied the autofan patch but it still seems to ignore my memory temp target and only focuses on the core temp target. Do I need to reboot the system or something?

**Comment by dedizones** [comment]
try:

`systemctl restart gddr6x_temps.service`

or Restart miner ?

last solution restart rig :/

same issue is open here for same problem: https://github.com/cryptopoo/hiveos_gddr6x_temps/issues/19

**Comment by cryptopoo** [comment]
Hello there,

if you dare opening a shell, you can launch

```
autofan screen
```

and this will show you a very nice screen with what autofan is doing. It could be that your core temps are already high and that's why it keeps acting on them.
What I suggest you is to check what autofan does after a fresh reboot.

If you see memory temperatures in the autofan screen, it is surely working with them, but the algorithm it uses is something that HiveOS wrote (which I think is very good, kudos to them), nothing different than that :)

**Comment by Chase817** [comment]
Thanks for the tip about `autofan screen`! I looked and saw that no memory temps were reported there. So I did the following:
1. Uninstalled the main memory temp add-on
2. Re-installed it (stable version)
3. Installed the autofan patch again on top
4. Restarted the miner

Now I see the mem temps in `autofan screen` and autofan looks to be working properly.

**Comment by cryptopoo** [comment]
I'm glad that worked for you (and also that you discovered how cool is the `autofan screen`!) :1st_place_medal: :partying_face: 

@mmll1, perhaps you can try the same steps as @Chase817 ?

**Comment by mmll1** [comment]
Yes, it works, thnx

**Comment by cryptopoo** [comment]
That's great, I'm glad it worked for you both!

If this script helped you anyhow and are happy with it, please consider a donation :pray: !

Cheers!
