### ISSUE TITLE
Forgot code or commit issues ?

### ISSUE THREAD

**Issue by dedizones** [cryptopoo/hiveos_gddr6x_temps#23]
hello

why  different to master on github and first release ?

i see last commit but in zip I don't have this new code

I take which I am lost by force

in github: https://github.com/cryptopoo/hiveos_gddr6x_temps/blob/main/opt/gddr6x_temps/gddr6x_temps

```
function loop() {
    while [[ TRUE ]]; do
        if [ -s "${GPU_STATS_JSON}" ]; then
            inotifywait -qq -e modify -t 12 "${GPU_STATS_JSON}"
```

In download Zip or Tar.gz

```
function loop() {
    while [[ TRUE ]]; do
        inotifywait -qq "${GPU_STATS_JSON}"
```

**Comment by cryptopoo** [comment]
Hi,

the concept of a release is to freeze code so that people that install a version can always relay on the same code.

Surely "main" is an active branch, I keep adding stuffs in it to make it better and more reliable. But sometimes I also break things and that means if you install from main branch directly, you may end up with a script that doesn't work.
If you are a first time user that just wants to try the script and you try it when I committed a boo-boo, you think "ah this thing doesn't work" and go away.

By fixing a release, I can ensure the code there is fixed, so people will always download that.

For testing, I have another installation script (quick-install-unstable.sh) which will always fetch latest code from the main branch.
So if you want to stay up to the code, you can keep installing from "unstable" and test. This will eventually produce feedback for me and I will know what to do better.

When the code in main reaches another "better" stage (and is going to be very soon) I will make a new release, so people installing from quick-install.sh will download new fresh code :)

Does it make sense to you?

**Comment by dedizones** [comment]
Ah ok nice
I will put unstable then to help you.
Thank you for your clear and clear answer.
