### ISSUE TITLE
"/run/hive/gpu-stats.json" - corupted after while

### ISSUE THREAD

**Issue by smdbg** [cryptopoo/hiveos_gddr6x_temps#25]
Hello , the file /run/hive/gpu-stats.json stucture is "broken" after while , then after some time goes back to normal 
here is the output of :  tail -f gpu-stats.json

![mem](https://user-images.githubusercontent.com/41722268/160989380-a24a3a47-beb7-49e7-afd9-551a11dced01.jpg)

as a result we see mem temps dissapear and reapear in hive web , autofan working sporadically (not human noticeable ).
My guess is that hiveos overwriting your script data input , some times your script is first , some times not

**Comment by nicjohnston** [comment]
This affects me as well.  First noticed it as the autofan patch only showing mem temps part of the time, didn't think to tail gpu stats.
Seem to me that the mem temps are only included in every other update of gpu-stats.json.  This is a naive comment, but perhaps there is a way to disable the hiveos service that writes to this file?
Edit: it's late, somehow I missed the corrupted part of the issue.  I can't reproduce that, but also haven't been looking for very long.
Edit2: reading #19 it sounds like there is a chance this was already fixed.  I'll try the unstable branch tomorrow and report back
![Screenshot from 2022-03-31 00-32-06](https://user-images.githubusercontent.com/5495209/160991167-8d09f9f7-7472-4092-9afc-92fa110d5cf6.png)

**Comment by cryptopoo** [comment]
Hello,

first of all, are you trying the module after the last patches of the 30th of March at ~1AM UTC?

In that version I introduced a patch that ensures that we run always before the agent sends data to HiveOS.

When @smdbg tails the file, what he sees is correct: the file initially is the mere result of the `/hive/bin/gpu-stats` script. In less than a millisecond after its modification, our script patches the gpu-stats file. This is the reason why if you tail -follow the file you will see 2 versions of it alternating continously. This is perfectly normal.

What you can read on the script /opt/gddr6x_temps/gddr6x_temps on line 78 of latest version, is a line that touches and modify the mtime (modification time) of the gpu-stats.json to something 3 seconds ago since it was detected the first modification.

This because the HiveOS agent when asks gpu-stats to gather information, waits for modifications to the gpu-stats.json file by checking that the modification time on it is less than 1 second. If it sees that the gpu-stats file was modified within last second, then it continues and sends the data to HiveOS.
As soon as the file is firstly modified, instead, we change the file modification time to 3 seconds back in time. This will ensure that the agent waiting for the results will not see the modification of gpu-stats.json until we are actually done patching it.

For this reason, you should not see anymore any temperature disappearing in the GUI, unless, of course, the miner is not reporting it.

So this is why my question whether you re-installed the script any time after March 30th, since after that day it shouldn't happen anymore.

In the current unstable branch, the "tricking" time is increased to 5 seconds to allow for even more time to act before HiveOS can "see" that data.

So please let me know whether you experience this in the very last stable version, or you were on a previous one.

Additionally, please install the unstable version, that has a slightly increased time, since each machine might be faster or slower and 5 seconds should definitely be enough for most of the machines.

Cheers!

**Comment by cryptopoo** [comment]
@nicjohnston indeed this might have been fixed already :)

But stay assured that tailing the gpu-stats.json file, will always produce the original version and the patched version.
